development:
  adapter: postgresql
  encoding: unicode
  database: brewber_dev
  pool: 5
  username: brewber
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: brewber_test
  pool: 5
  username: brewber
  password: password1

# production:
#   <<: *default
#   database: db/production.sqlite3
