# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da9dc6306f12aed681c79c443a3100d0c36c1f5a09682b02d80682930bd1d5191a34180f0879202e7c674955b66b223f5d333e7960aa2086ab079d3585eda3f9

test:
  secret_key_base: 2a8f194952f26dd1e36bbaa53dfcc7e75156419bbec8e6e4d7bb361e55ec0a10e4d1f35767b57db6b4d2ec389c76947905060f15db3d0a3c9825a85f488b88cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
