# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8db9205b1f8e46f9b9c25f0b17ad957e4d5611c4c451afad759d58a7e06b2a59a4a6b81208928c5f8fcef385473bde220959947da8d5f8dfe9a80ce608d5ae2f

test:
  secret_key_base: aca4c7f842fb0d031056ad3d146028c6e9f4d14e4d21746018695fe725e9156c8f8ea656c948fe70046b94525e8b0599b664f666c1c12a1261f567bccc03cc60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
